update-ssh-job:
  stage: deploy
  image: alpine
  before_script:
    #Installera saker som vi behöver (NPM är redan installerat)
    - apk add git
    - apk add openssh
    - apk add --no-cache lftp
    - apk add sshpass
    - apk add lftp
  script:
    #Lägg till hem.ssis.nu till listan med kända värdnamn
    - mkdir /root/.ssh
    - chmod 700 /root/.ssh
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - ssh-keyscan -H hem.ssis.nu >> /root/.ssh/known_hosts
    #Skriv ut lite debugging
    - echo "[DEBUGGING!] Debug - mappinnehåll:"
    - ls
    #Pusha hemsidesinnehåll
    - echo "[PÅ G!] Pushar hemsidan till hem.ssis.nu..."
    - echo "[PÅ G!] Laddar upp till server..."
    - lftp -e "mirror -e -P 4 -R --transfer-all --reverse ./dist /public_html/Bootstrap/ --verbose; quit" -u "$SFTP_USERNAME,$SFTP_PASSWORD" sftp://hem.ssis.nu -p 22
    - echo "[YAY! KLAR!] Hemsidan uppladdad!"
  timeout: 2min
